setwd(here::here())
library(tidyverse)
library(ggplot2)
library(cowplot)
library(edgeR)
source("r_code/functions.R")
theme_set(theme_bw(base_size = 9))

source("r_code/isomir_commonality/bcbio_isomir_commonality.R")
source("r_code/isomir_commonality/mirge_isomir_commonality.R")
source("r_code/isomir_commonality/isomirsea_isomir_commonality.R")
source("r_code/isomir_commonality/srnabench_isomir_commonality.R")
